"""add days table

Revision ID: 1bb3adf4f447
Revises: a9c3e7d1b5f8
Create Date: 2026-09-12 23:45:33.548563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb3adf4f447'
down_revision: Union[str, Sequence[str], None] = 'a9c3e7d1b5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('repeat', sa.String(length=10), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_days_user_id'), 'days', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_days_user_id'), table_name='days')
    op.drop_table('days')
    # ### end Alembic commands ###
