"""add deleted_at to books

Revision ID: aac8dc45ab3d
Revises: a19886b0a614
Create Date: 2026-08-08 14:05:36.349444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac8dc45ab3d'
down_revision: Union[str, Sequence[str], None] = 'a19886b0a614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_books_deleted_at'), 'books', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_deleted_at'), table_name='books')
    op.drop_column('books', 'deleted_at')
    # ### end Alembic commands ###
