"""add owner_id to vocab_books

Revision ID: c9042b44cc6e
Revises: eccd156c4e9c
Create Date: 2026-09-14 08:48:24.955913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9042b44cc6e'
down_revision: Union[str, Sequence[str], None] = 'eccd156c4e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_books', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vocab_books_owner_id'), 'vocab_books', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocab_books_owner_id'), table_name='vocab_books')
    op.drop_column('vocab_books', 'owner_id')
    # ### end Alembic commands ###
