"""add vocabulary tables

Revision ID: eccd156c4e9c
Revises: 1bb3adf4f447
Create Date: 2026-09-13 23:07:20.643877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccd156c4e9c'
down_revision: Union[str, Sequence[str], None] = '1bb3adf4f447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_book_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'word_id', name='uq_vocab_book_words')
    )
    op.create_index(op.f('ix_vocab_book_words_book_id'), 'vocab_book_words', ['book_id'], unique=False)
    op.create_index(op.f('ix_vocab_book_words_word_id'), 'vocab_book_words', ['word_id'], unique=False)
    op.create_table('vocab_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('vocab_practice_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('wrong_times', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_practice_logs_session_id'), 'vocab_practice_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_vocab_practice_logs_user_id'), 'vocab_practice_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_vocab_practice_logs_word_id'), 'vocab_practice_logs', ['word_id'], unique=False)
    op.create_table('vocab_practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_practice_sessions_user_id'), 'vocab_practice_sessions', ['user_id'], unique=False)
    op.create_table('vocab_word_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('right_count', sa.Integer(), nullable=False),
    sa.Column('wrong_active', sa.Boolean(), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_vocab_word_progress')
    )
    op.create_index(op.f('ix_vocab_word_progress_due'), 'vocab_word_progress', ['due'], unique=False)
    op.create_index(op.f('ix_vocab_word_progress_user_id'), 'vocab_word_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_vocab_word_progress_word_id'), 'vocab_word_progress', ['word_id'], unique=False)
    op.create_table('vocab_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic_uk', sa.String(length=100), nullable=False),
    sa.Column('phonetic_us', sa.String(length=100), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('sentences', sa.JSON(), nullable=False),
    sa.Column('phrases', sa.JSON(), nullable=False),
    sa.Column('synos', sa.JSON(), nullable=False),
    sa.Column('rel_words', sa.JSON(), nullable=False),
    sa.Column('freq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_words')
    op.drop_index(op.f('ix_vocab_word_progress_word_id'), table_name='vocab_word_progress')
    op.drop_index(op.f('ix_vocab_word_progress_user_id'), table_name='vocab_word_progress')
    op.drop_index(op.f('ix_vocab_word_progress_due'), table_name='vocab_word_progress')
    op.drop_table('vocab_word_progress')
    op.drop_index(op.f('ix_vocab_practice_sessions_user_id'), table_name='vocab_practice_sessions')
    op.drop_table('vocab_practice_sessions')
    op.drop_index(op.f('ix_vocab_practice_logs_word_id'), table_name='vocab_practice_logs')
    op.drop_index(op.f('ix_vocab_practice_logs_user_id'), table_name='vocab_practice_logs')
    op.drop_index(op.f('ix_vocab_practice_logs_session_id'), table_name='vocab_practice_logs')
    op.drop_table('vocab_practice_logs')
    op.drop_table('vocab_books')
    op.drop_index(op.f('ix_vocab_book_words_word_id'), table_name='vocab_book_words')
    op.drop_index(op.f('ix_vocab_book_words_book_id'), table_name='vocab_book_words')
    op.drop_table('vocab_book_words')
    # ### end Alembic commands ###
