"""assistant message type + plans table

Revision ID: ef1c48d8ee84
Revises: c4ba28cc4db6
Create Date: 2026-08-10 17:39:02.281991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1c48d8ee84'
down_revision: Union[str, Sequence[str], None] = 'c4ba28cc4db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=32), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_plans_plan_id'), 'assistant_plans', ['plan_id'], unique=True)
    op.create_index(op.f('ix_assistant_plans_session_id'), 'assistant_plans', ['session_id'], unique=False)
    op.create_index(op.f('ix_assistant_plans_user_id'), 'assistant_plans', ['user_id'], unique=False)
    op.add_column('assistant_messages', sa.Column('type', sa.String(length=20), nullable=False, server_default='text'))
    # 存量数据：将含 planId/confirmPlanId 的 assistant 消息标记为 confirm_request
    # MySQL 用 JSON_EXTRACT；SQLite 走 create_all 无存量，此条件无副作用
    op.execute(
        "UPDATE assistant_messages SET type = 'confirm_request' "
        "WHERE role = 'assistant' AND type = 'text' "
        "AND meta IS NOT NULL "
        "AND (JSON_EXTRACT(meta, '$.planId') IS NOT NULL "
        "     OR JSON_EXTRACT(meta, '$.confirmPlanId') IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_messages', 'type')
    op.drop_index(op.f('ix_assistant_plans_user_id'), table_name='assistant_plans')
    op.drop_index(op.f('ix_assistant_plans_session_id'), table_name='assistant_plans')
    op.drop_index(op.f('ix_assistant_plans_plan_id'), table_name='assistant_plans')
    op.drop_table('assistant_plans')
    # ### end Alembic commands ###
